### ISSUE TITLE
This does not work, as `Parameters` requires `StringList`

### ISSUE THREAD

**Issue by dz902** [aws-samples/amazon-stepfunctions-ssm-waitfortasktoken#1]
I'm not sure whether this has ever worked, because `SendCommand` and `StartAutomationExecution` both requires `StringList` for `Parameter`. This makes it impossible to use the `blah.$` trick as the Step Function definition will fail at first execution.

**Comment by elelkhoury** [comment]
Hi @dz902, this code repository is actually linked to a prescriptive guidance link here https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/run-aws-systems-manager-automation-tasks-synchronously-from-aws-step-functions.html

A sample step function is also provided for you to test and adapt thereafter. 

if you're looking to use jsonPath to dynamically reference items, you can always combine this with States.Array intrinsic functions to achieve this. https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html

`"InstanceIds.$": "States.Array($.StatePayload.detail.EC2InstanceId)"`

If you are still facing any other issues, feel free to get back to us on this thread with more details on your use case and error you are facing.
