### ISSUE TITLE
Need to support AWS-RunPowerShellScript for windows machines

### ISSUE THREAD

**Issue by melwinpais** [aws-samples/amazon-stepfunctions-ssm-waitfortasktoken#4]

**Comment by elelkhoury** [comment]
Hi Melwin, we are looking into adding support for AWS-RunPowerShellScript. Thank you for raising this

**Comment by elelkhoury** [comment]
Hi @melwinpais , please feel free to test and send us your feedback. We have included a new parameter shell that takes two value (shell or powershell) which would indicate which should be used to execute the Commands on the EC2 instances
